package ua.kiev.kvartirant.model.enums;

public enum FlatLocation {
    ALL, HOLOSIIVSKYI, DARNYTSKIY, DESNYANSKIY, DNIPRO, OBOLONSKIY,
    PECHERSKIY, PODOLSKY, SVYATOSHINSKIY, SOLOMENSKIY, SHEVCHENKO
}
